### ISSUE TITLE
E11000 duplicate key error collection: strava-bot.users index: user_id_1_team_id_1 dup key

### ISSUE THREAD

**Issue by dblock** [dblock/slack-strava#22]
```
E, [2018-04-12T21:15:15.749146 #232] ERROR -- : E11000 duplicate key error collection: strava-bot.users index: user_id_1_team_id_1 dup key: { : "U02CZCQJC", : ObjectId('5abdc5a4afe25400ea863648') } (11000) (Mongo::Error::OperationFailure)
/app/vendor/bundle/ruby/2.3.0/gems/mongo-2.5.1/lib/mongo/operation/result.rb:256:in `validate!'
/app/vendor/bundle/ruby/2.3.0/gems/mongo-2.5.1/lib/mongo/operation/write/insert.rb:58:in `execute_write_command'
/app/vendor/bundle/ruby/2.3.0/gems/mongo-2.5.1/lib/mongo/operation/write/write_command_enabled.rb:48:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/mongo-2.5.1/lib/mongo/collection.rb:433:in `block (2 levels) in insert_one'
/app/vendor/bundle/ruby/2.3.0/gems/mongo-2.5.1/lib/mongo/retryable.rb:150:in `legacy_write_with_retry'
/app/vendor/bundle/ruby/2.3.0/gems/mongo-2.5.1/lib/mongo/retryable.rb:103:in `write_with_retry'
/app/vendor/bundle/ruby/2.3.0/gems/mongo-2.5.1/lib/mongo/collection.rb:422:in `block in insert_one'
/app/vendor/bundle/ruby/2.3.0/gems/mongo-2.5.1/lib/mongo/cluster.rb:515:in `with_session'
/app/vendor/bundle/ruby/2.3.0/gems/mongo-2.5.1/lib/mongo/client.rb:449:in `with_session'
/app/vendor/bundle/ruby/2.3.0/gems/mongo-2.5.1/lib/mongo/collection.rb:421:in `insert_one'
/app/vendor/bundle/ruby/2.3.0/gems/mongoid-7.0.0/lib/mongoid/query_cache.rb:182:in `insert_one_with_clear_cache'
/app/vendor/bundle/ruby/2.3.0/gems/mongoid-7.0.0/lib/mongoid/persistable/creatable.rb:81:in `insert_as_root'
/app/vendor/bundle/ruby/2.3.0/gems/mongoid-7.0.0/lib/mongoid/persistable/creatable.rb:27:in `block in insert'
/app/vendor/bundle/ruby/2.3.0/gems/mongoid-7.0.0/lib/mongoid/persistable/creatable.rb:120:in `block (2 levels) in prepare_insert'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:131:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/mongoid-7.0.0/lib/mongoid/interceptable.rb:132:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/mongoid-7.0.0/lib/mongoid/persistable/creatable.rb:119:in `block in prepare_insert'
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:97:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/mongoid-7.0.0/lib/mongoid/interceptable.rb:132:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/mongoid-7.0.0/lib/mongoid/persistable/creatable.rb:118:in `prepare_insert'
/app/vendor/bundle/ruby/2.3.0/gems/mongoid-7.0.0/lib/mongoid/persistable/creatable.rb:23:in `insert'
/app/vendor/bundle/ruby/2.3.0/gems/mongoid-7.0.0/lib/mongoid/persistable/creatable.rb:180:in `block in create!'
/app/vendor/bundle/ruby/2.3.0/gems/mongoid-7.0.0/lib/mongoid/threaded/lifecycle.rb:161:in `_creating'
/app/vendor/bundle/ruby/2.3.0/gems/mongoid-7.0.0/lib/mongoid/persistable/creatable.rb:175:in `create!'
/app/slack-strava/models/user.rb:49:in `find_create_or_update_by_slack_id!'
/app/slack-strava/server.rb:10:in `block in <class:Server>'
/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-bot-0.11.0/lib/slack-ruby-bot/hooks/set.rb:33:in `block (2 levels) in register_callback'
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/set.rb:306:in `each_key'
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/set.rb:306:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-bot-0.11.0/lib/slack-ruby-bot/hooks/set.rb:32:in `block in register_callback'
/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/real_time/client.rb:199:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/real_time/client.rb:198:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/real_time/client.rb:198:in `run_callbacks'
/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/real_time/client.rb:177:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/real_time/client.rb:93:in `block (2 levels) in run_loop'
/app/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.7.0/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
/app/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.7.0/lib/websocket/driver/event_emitter.rb:38:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.7.0/lib/websocket/driver/event_emitter.rb:38:in `emit'
/app/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.7.0/lib/websocket/driver/hybi.rb:398:in `emit_message'
/app/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.7.0/lib/websocket/driver/hybi.rb:381:in `emit_frame'
/app/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.7.0/lib/websocket/driver/hybi.rb:123:in `parse'
/app/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.7.0/lib/websocket/driver/client.rb:63:in `parse'
/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.11.1/lib/slack/real_time/concurrency/celluloid.rb:61:in `handle_read'
/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by dblock** [comment]
Dunno, haven't seen in a long time.
