### ISSUE TITLE
TypeError: can't convert nil into an exact number

### ISSUE THREAD

**Issue by dblock** [dblock/slack-strava#54]
```
E, [2018-11-21T02:36:57.172244 #236] ERROR -- : TypeError: can't convert nil into an exact number
  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/core_ext/time/calculations.rb:53:in `at'
  /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/core_ext/time/calculations.rb:53:in `at_with_coercion'
  /app/slack-strava/models/user.rb:99:in `connect!'
  /app/slack-strava/api/endpoints/users_endpoint.rb:18:in `block (2 levels) in <class:UsersEndpoint>'
  /app/vendor/bundle/ruby/2.3.0/gems/grape-1.1.0/lib/grape/endpoint.rb:57:in `call'
  /app/vendor/bundle/ruby/2.3.0/gems/grape-1.1.0/lib/grape/endpoint.rb:57:in `block (2 levels) in generate_api_method'
```

**Comment by dblock** [comment]
Catch earlier, but still unexplained why and how, https://github.com/dblock/slack-strava/commit/5b8462caa04b27d73f2a2fac98b494fe4d7d035c.

**Comment by dblock** [comment]
The original crash (`TypeError: cant convert nil into an exact number` in `user.rb#connect!`) was partially addressed in 5b8462c, which added defensive raises for missing `access_token`, `refresh_token`, and `expires_at` in the OAuth response.

Since then, `connect!` has been removed entirely and OAuth token handling has been refactored into `strava_tokens.rb#refresh_access_token!`, which already contains equivalent defensive checks. The original crash path no longer exists. Closing as resolved.
