### ISSUE TITLE
404 retrieving activity after webhook 

### ISSUE THREAD

**Issue by dblock** [dblock/slack-strava#83]
Over the last 7 days I saw 34 instances of these over 5712 events, so I looked at the sequence and found several that looked like so:

```
I, [2020-04-07T07:50:42.104265 #258]  INFO -- : aspect_type=create
I, [2020-04-07T07:51:44.877991 #258]  INFO -- : another aspect_type=create, same activity
I, [2020-04-07T07:52:59.057450 #258]  INFO -- : another aspect_type=create, same activity, but this time a 404
... never see this activity again
```

Discussion in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/strava-api/qk-wF04rEnM

Retry on the 404.

**Comment by dblock** [comment]
```
I, [2020-04-07T07:52:59.057450 #258]  INFO -- : Syncing ...
W, [2020-04-07T07:53:00.197972 #258]  WARN -- : Error in team ..., the server responded with status 404, /app/vendor/bundle/ruby/2.6.0/gems/strava-ruby-client-0.3.2/lib/strava/web/raise_error.rb:10:in `on_complete'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/response.rb:9:in `block in call'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/response.rb:61:in `on_complete'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/request/url_encoded.rb:15:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/request/multipart.rb:15:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
/app/vendor/bundle/ruby/2.6.0/gems/strava-ruby-client-0.3.2/lib/strava/web/request.rb:26:in `request'
/app/vendor/bundle/ruby/2.6.0/gems/strava-ruby-client-0.3.2/lib/strava/web/request.rb:5:in `get'
/app/vendor/bundle/ruby/2.6.0/gems/strava-ruby-client-0.3.2/lib/strava/api/endpoints/activities.rb:20:in `activity'
/app/slack-strava/models/user.rb:211:in `rebrag_last_activity!'
/app/slack-strava/models/user.rb:189:in `block in rebrag!'
/app/slack-strava/models/brag.rb:3:in `with_strava_error_handler'
/app/slack-strava/models/user.rb:188:in `rebrag!'
/app/slack-strava/app.rb:123:in `block (2 levels) in users_brag_and_rebrag!'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.0/lib/mongoid/contextual/mongo.rb:710:in `yield_document'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.0/lib/mongoid/contextual/mongo.rb:137:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.11.4/lib/mongo/collection/view/iterable.rb:51:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.11.4/lib/mongo/cursor.rb:154:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.11.4/lib/mongo/cursor.rb:152:in `loop'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.11.4/lib/mongo/cursor.rb:152:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.11.4/lib/mongo/collection/view/iterable.rb:50:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.0/lib/mongoid/query_cache.rb:227:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.0/lib/mongoid/contextual/mongo.rb:136:in `each'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/app/slack-strava/app.rb:120:in `block in users_brag_and_rebrag!'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.0/lib/mongoid/contextual/mongo.rb:710:in `yield_document'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.0/lib/mongoid/contextual/mongo.rb:137:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.11.4/lib/mongo/collection/view/iterable.rb:51:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.11.4/lib/mongo/cursor.rb:154:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.11.4/lib/mongo/cursor.rb:152:in `loop'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.11.4/lib/mongo/cursor.rb:152:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.11.4/lib/mongo/collection/view/iterable.rb:50:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.0/lib/mongoid/query_cache.rb:227:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.0/lib/mongoid/contextual/mongo.rb:136:in `each'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/app/slack-strava/app.rb:113:in `users_brag_and_rebrag!'
/app/slack-strava/app.rb:18:in `block (2 levels) in after_start!'
/app/slack-strava/app.rb:47:in `block (2 levels) in continuously'
/app/slack-strava/app.rb:46:in `loop'
```
